import "./globals.css";


export const metadata = {
  title: "AI Agent Company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
          {children}
      </body>
    </html>
  );
}
